# Generated by Django 4.1.5 on 2023-01-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube_history', '0004_data_after_additional_potential_options_grade_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='after_additional_potential_options_grade_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_additional_potential_options_grade_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_additional_potential_options_grade_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_additional_potential_options_value_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_additional_potential_options_value_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_additional_potential_options_value_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_potential_options_grade_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_potential_options_grade_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_potential_options_grade_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_potential_options_value_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_potential_options_value_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='after_potential_options_value_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_additional_potential_options_grade_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_additional_potential_options_grade_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_additional_potential_options_grade_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_additional_potential_options_value_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_additional_potential_options_value_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_additional_potential_options_value_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_potential_options_grade_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_potential_options_grade_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_potential_options_grade_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_potential_options_value_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_potential_options_value_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='before_potential_options_value_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
